/**
 * ATTENTION. This code was AUTO GENERATED by schema2typebox.
 * While I don't know your use case, there is a high chance that direct changes
 * to this file get lost. Consider making changes to the underlying JSON schema
 * you use to generate this file instead. The default file is called
 * "schema.json", perhaps have a look there! :]
 */
import { Type } from '@sinclair/typebox'

export const Field = Type.Object(
  {
    docId: Type.String({
      description: 'Hex-encoded 32-byte buffer',
      minLength: 1,
    }),
    versionId: Type.String({
      description:
        "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
      minLength: 1,
    }),
    originalVersionId: Type.String({
      description:
        'Version ID of the original version of this document. For the original version, matches `versionId`.',
      minLength: 1,
    }),
    schemaName: Type.Literal('field', { description: 'Must be `field`' }),
    createdAt: Type.String({
      description:
        'RFC3339-formatted datetime of when the first version of the element was created',
      format: 'date-time',
    }),
    updatedAt: Type.String({
      description:
        'RFC3339-formatted datetime of when this version of the element was created',
      format: 'date-time',
    }),
    links: Type.Array(Type.String(), {
      description:
        "Version ids of the previous document versions this one is replacing. Each link is id (hex-encoded 32 byte buffer) and index number, separated by '/'",
      uniqueItems: true,
    }),
    deleted: Type.Boolean({
      description: 'Indicates whether the document has been deleted',
    }),
    tagKey: Type.String({
      description: 'They key in a tags object that this field applies to',
      minLength: 1,
    }),
    type: Type.Union(
      [
        Type.Literal('type_unspecified'),
        Type.Literal('text'),
        Type.Literal('number'),
        Type.Literal('selectOne'),
        Type.Literal('selectMultiple'),
        Type.Literal('UNRECOGNIZED'),
      ],
      {
        description:
          'Type of field - defines how the field is displayed to the user.',
        'meta:enum': {
          type_unspecified:
            'for backwards compatibility, unspecified type of appearance',
          text: 'Freeform text field',
          number: 'Allows only numbers',
          selectOne: 'Select one item from a list of pre-defined options',
          selectMultiple:
            'Select any number of items from a list of pre-defined options',
        },
      },
    ),
    label: Type.String({
      description: 'Default language label for the form field label',
      minLength: 1,
    }),
    appearance: Type.Optional(
      Type.Union(
        [
          Type.Literal('appearance_unspecified'),
          Type.Literal('singleline'),
          Type.Literal('multiline'),
          Type.Literal('UNRECOGNIZED'),
        ],
        {
          description:
            'For text fields, display as a single-line or multi-line field',
          'meta:enum': {
            appearance_unspecified:
              'for backwards compatibility, unspecified type of appearance',
            singleline: 'Text will be cut-off if more than one line',
            multiline: 'Text will wrap to multiple lines within text field',
          },
          default: 'multiline',
        },
      ),
    ),
    snakeCase: Type.Optional(
      Type.Boolean({
        description:
          'Convert field value into snake_case (replace spaces with underscores and convert to lowercase)',
        default: false,
      }),
    ),
    options: Type.Optional(
      Type.Array(
        Type.Object({
          label: Type.String({ minLength: 1 }),
          value: Type.Union([
            Type.String(),
            Type.Boolean(),
            Type.Number(),
            Type.Null(),
          ]),
        }),
        {
          description:
            'List of options the user can select for single- or multi-select fields',
        },
      ),
    ),
    universal: Type.Optional(
      Type.Boolean({
        description:
          'If true, this field will appear in the Add Field list for all presets',
        default: false,
      }),
    ),
    placeholder: Type.Optional(
      Type.String({
        description:
          "Displayed as a placeholder in an empty text or number field before the user begins typing. Use 'helperText' for important information, because the placeholder is not visible after the user has entered data.",
      }),
    ),
    helperText: Type.Optional(
      Type.String({
        description:
          'Additional context about the field, e.g. hints about how to answer the question.',
      }),
    ),
    createdBy: Type.Optional(Type.String()),
    updatedBy: Type.Optional(Type.String()),
  },
  {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: 'http://mapeo.world/schemas/field/v1.json',
    description:
      'A field defines a form field that will be shown to the user when creating or editing a map entity. Presets define which fields are shown to the user for a particular map entity. The field definition defines whether the field should show as a text box, multiple choice, single-select, etc. It defines what tag-value is set when the field is entered.',
    additionalProperties: false,
  },
)
