/**
 * ATTENTION. This code was AUTO GENERATED by schema2typebox.
 * While I don't know your use case, there is a high chance that direct changes
 * to this file get lost. Consider making changes to the underlying JSON schema
 * you use to generate this file instead. The default file is called
 * "schema.json", perhaps have a look there! :]
 */
import { Type } from '@sinclair/typebox'

export const Icon = Type.Object(
  {
    docId: Type.String({
      description: 'Hex-encoded 32-byte buffer',
      minLength: 1,
    }),
    versionId: Type.String({
      description:
        "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
      minLength: 1,
    }),
    originalVersionId: Type.String({
      description:
        'Version ID of the original version of this document. For the original version, matches `versionId`.',
      minLength: 1,
    }),
    schemaName: Type.Literal('icon', { description: 'Must be `icon`' }),
    createdAt: Type.String({
      description:
        'RFC3339-formatted datetime of when the first version of the element was created',
      format: 'date-time',
    }),
    updatedAt: Type.String({
      description:
        'RFC3339-formatted datetime of when this version of the element was created',
      format: 'date-time',
    }),
    links: Type.Array(Type.String(), {
      description:
        "Version ids of the previous document versions this one is replacing. Each link is id (hex-encoded 32 byte buffer) and index number, separated by '/'",
      uniqueItems: true,
    }),
    deleted: Type.Boolean({
      description: 'Indicates whether the document has been deleted',
    }),
    name: Type.String({ minLength: 1 }),
    variants: Type.Array(Type.Unknown()),
  },
  {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: 'http://mapeo.world/schemas/icon/v1.json',
    description: 'An Icon represents metadata to retrieve an Icon blob',
    definitions: {
      size: {
        type: 'string',
        enum: ['size_unspecified', 'small', 'medium', 'large'],
      },
      blobVersionId: {
        description:
          "Version id of the icon blob. Each id is id (hex-encoded 32 byte buffer) and index number, separated by '/'",
        type: 'string',
        minLength: 1,
      },
    },
    additionalProperties: false,
  },
)
