/**
 * ATTENTION. This code was AUTO GENERATED by schema2typebox.
 * While I don't know your use case, there is a high chance that direct changes
 * to this file get lost. Consider making changes to the underlying JSON schema
 * you use to generate this file instead. The default file is called
 * "schema.json", perhaps have a look there! :]
 */
import { Type } from '@sinclair/typebox'

export const Observation = Type.Object(
  {
    docId: Type.String({
      description: 'Hex-encoded 32-byte buffer',
      minLength: 1,
    }),
    versionId: Type.String({
      description:
        "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
      minLength: 1,
    }),
    originalVersionId: Type.String({
      description:
        'Version ID of the original version of this document. For the original version, matches `versionId`.',
      minLength: 1,
    }),
    schemaName: Type.Literal('observation', {
      description: 'Must be `observation`',
    }),
    createdAt: Type.String({
      description:
        'RFC3339-formatted datetime of when the first version of the element was created',
      format: 'date-time',
    }),
    updatedAt: Type.String({
      description:
        'RFC3339-formatted datetime of when this version of the element was created',
      format: 'date-time',
    }),
    links: Type.Array(Type.String(), {
      description:
        "Version ids of the previous document versions this one is replacing. Each link is id (hex-encoded 32 byte buffer) and index number, separated by '/'",
      uniqueItems: true,
    }),
    deleted: Type.Boolean({
      description: 'Indicates whether the document has been deleted',
    }),
    lat: Type.Optional(
      Type.Number({
        description: 'latitude of the observation',
        minimum: -90,
        maximum: 90,
      }),
    ),
    lon: Type.Optional(
      Type.Number({
        description: 'longitude of the observation',
        minimum: -180,
        maximum: 180,
      }),
    ),
    attachments: Type.Array(
      Type.Object({
        url: Type.Optional(
          Type.String({ description: 'Path to fetching attachment data' }),
        ),
      }),
      {
        description:
          'media or other data that are attached to this observation',
      },
    ),
    tags: Type.Object(
      {},
      {
        description:
          'User-defined key-value pairs relevant to this observation',
        additionalProperties: {
          anyOf: [
            { type: 'boolean' },
            { type: 'number' },
            { type: 'string' },
            { type: 'null' },
            {
              type: 'array',
              items: {
                anyOf: [
                  { type: 'boolean' },
                  { type: 'number' },
                  { type: 'string' },
                  { type: 'null' },
                ],
              },
            },
          ],
        },
      },
    ),
    metadata: Type.Optional(
      Type.Object(
        {
          manualLocation: Type.Optional(
            Type.Boolean({
              description: 'Whether location has been set manually',
              default: false,
            }),
          ),
          position: Type.Optional(
            Type.Object(
              {
                timestamp: Type.String({
                  description:
                    'Timestamp of when the current position was obtained',
                  format: 'date-time',
                }),
                mocked: Type.Optional(
                  Type.Boolean({
                    description: '`true` if the position was mocked',
                    default: false,
                  }),
                ),
                coords: Type.Object(
                  {
                    latitude: Type.Number(),
                    longitude: Type.Number(),
                    altitude: Type.Optional(Type.Number()),
                    altitudeAccuracy: Type.Optional(Type.Number()),
                    heading: Type.Optional(Type.Number()),
                    speed: Type.Optional(Type.Number()),
                    accuracy: Type.Optional(Type.Number()),
                  },
                  {
                    description:
                      'Position details, should be self explanatory. Units in meters',
                  },
                ),
              },
              { description: 'Position details' },
            ),
          ),
          lastSavedPosition: Type.Optional(
            Type.Object(
              {
                timestamp: Type.String({
                  description:
                    'Timestamp of when the current position was obtained',
                  format: 'date-time',
                }),
                mocked: Type.Optional(
                  Type.Boolean({
                    description: '`true` if the position was mocked',
                    default: false,
                  }),
                ),
                coords: Type.Object(
                  {
                    latitude: Type.Number(),
                    longitude: Type.Number(),
                    altitude: Type.Optional(Type.Number()),
                    altitudeAccuracy: Type.Optional(Type.Number()),
                    heading: Type.Optional(Type.Number()),
                    speed: Type.Optional(Type.Number()),
                    accuracy: Type.Optional(Type.Number()),
                  },
                  {
                    description:
                      'Position details, should be self explanatory. Units in meters',
                  },
                ),
              },
              { description: 'Position details' },
            ),
          ),
          positionProvider: Type.Optional(
            Type.Object(
              {
                gpsAvailable: Type.Optional(
                  Type.Boolean({
                    description:
                      'Whether the user has enabled GPS for device location (this is not the same as whether location is turned on or off, this is a device setting whether to use just wifi and bluetooth or use GPS for location)',
                  }),
                ),
                passiveAvailable: Type.Optional(
                  Type.Boolean({
                    description:
                      'Whether the device is configured to lookup location based on wifi and bluetooth networks',
                  }),
                ),
                locationServicesEnabled: Type.Boolean({
                  description:
                    'Has the user enabled location services on the device (this is often turned off when the device is in airplane mode)',
                }),
                networkAvailable: Type.Optional(
                  Type.Boolean({
                    description:
                      'Whether the device can lookup location based on cell phone towers',
                  }),
                ),
              },
              {
                description:
                  'Details of the location providers that were available on the device when the observation was recorded',
              },
            ),
          ),
        },
        {
          description:
            'Additional metadata associated with the observation (e.g. location precision, altitude, heading)',
          additionalProperties: false,
        },
      ),
    ),
    presetRef: Type.Optional(
      Type.Object(
        {
          docId: Type.String({
            description:
              'hex-encoded id of the element that this observation references',
            minLength: 1,
          }),
          versionId: Type.String({
            description:
              "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
            minLength: 1,
          }),
        },
        {
          description:
            'References to the preset that this observation is related to.',
        },
      ),
    ),
  },
  {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: 'http://mapeo.world/schemas/observation/v1.json',
    description:
      "An observation is something that has been observed at a particular time and place. It is a subjective statement of 'I saw/heard this, here'",
    definitions: {
      attachment: {
        type: 'object',
        properties: {
          url: {
            type: 'string',
            description: 'Path to fetching attachment data',
          },
        },
      },
      position: {
        description: 'Position details',
        type: 'object',
        required: ['timestamp', 'coords'],
        properties: {
          timestamp: {
            description: 'Timestamp of when the current position was obtained',
            type: 'string',
            format: 'date-time',
          },
          mocked: {
            description: '`true` if the position was mocked',
            type: 'boolean',
            default: false,
          },
          coords: {
            description:
              'Position details, should be self explanatory. Units in meters',
            type: 'object',
            required: ['latitude', 'longitude'],
            properties: {
              latitude: { type: 'number' },
              longitude: { type: 'number' },
              altitude: { type: 'number' },
              altitudeAccuracy: { type: 'number' },
              heading: { type: 'number' },
              speed: { type: 'number' },
              accuracy: { type: 'number' },
            },
          },
        },
      },
    },
    additionalProperties: false,
  },
)
