/**
 * ATTENTION. This code was AUTO GENERATED by schema2typebox.
 * While I don't know your use case, there is a high chance that direct changes
 * to this file get lost. Consider making changes to the underlying JSON schema
 * you use to generate this file instead. The default file is called
 * "schema.json", perhaps have a look there! :]
 */
import { Type } from '@sinclair/typebox'

export const Preset = Type.Object(
  {
    docId: Type.String({
      description: 'Hex-encoded 32-byte buffer',
      minLength: 1,
    }),
    versionId: Type.String({
      description:
        "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
      minLength: 1,
    }),
    originalVersionId: Type.String({
      description:
        'Version ID of the original version of this document. For the original version, matches `versionId`.',
      minLength: 1,
    }),
    schemaName: Type.Literal('preset', { description: 'Must be `preset`' }),
    createdAt: Type.String({
      description:
        'RFC3339-formatted datetime of when the first version of the element was created',
      format: 'date-time',
    }),
    updatedAt: Type.String({
      description:
        'RFC3339-formatted datetime of when this version of the element was created',
      format: 'date-time',
    }),
    links: Type.Array(Type.String(), {
      description:
        "Version ids of the previous document versions this one is replacing. Each link is id (hex-encoded 32 byte buffer) and index number, separated by '/'",
      uniqueItems: true,
    }),
    deleted: Type.Boolean({
      description: 'Indicates whether the document has been deleted',
    }),
    name: Type.String({
      description: 'Name for the feature in default language.',
    }),
    geometry: Type.Array(
      Type.Union([
        Type.Literal('point'),
        Type.Literal('vertex'),
        Type.Literal('line'),
        Type.Literal('area'),
        Type.Literal('relation'),
      ]),
      {
        description:
          'Valid geometry types for the feature - this preset will only match features of this geometry type `"point", "vertex", "line", "area", "relation"`',
        uniqueItems: true,
      },
    ),
    tags: Type.Record(
      Type.String(),
      Type.Union([
        Type.Boolean(),
        Type.Number(),
        Type.String(),
        Type.Null(),
        Type.Array(
          Type.Union([
            Type.Boolean(),
            Type.Number(),
            Type.String(),
            Type.Null(),
          ]),
        ),
      ]),
    ),
    addTags: Type.Record(
      Type.String(),
      Type.Union([
        Type.Boolean(),
        Type.Number(),
        Type.String(),
        Type.Null(),
        Type.Array(
          Type.Union([
            Type.Boolean(),
            Type.Number(),
            Type.String(),
            Type.Null(),
          ]),
        ),
      ]),
    ),
    removeTags: Type.Record(
      Type.String(),
      Type.Union([
        Type.Boolean(),
        Type.Number(),
        Type.String(),
        Type.Null(),
        Type.Array(
          Type.Union([
            Type.Boolean(),
            Type.Number(),
            Type.String(),
            Type.Null(),
          ]),
        ),
      ]),
    ),
    fieldRefs: Type.Array(
      Type.Object({
        docId: Type.String({
          description:
            'hex-encoded id of the element that this observation references',
          minLength: 1,
        }),
        versionId: Type.String({
          description:
            "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
          minLength: 1,
        }),
      }),
      {
        description: 'References to any fields that this preset is related to.',
      },
    ),
    iconRef: Type.Optional(
      Type.Object(
        {
          docId: Type.String({
            description:
              'hex-encoded id of the element that this observation references',
            minLength: 1,
          }),
          versionId: Type.String({
            description:
              "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
            minLength: 1,
          }),
        },
        {
          description: 'References to the icon that this preset is related to.',
        },
      ),
    ),
    terms: Type.Array(Type.String(), {
      description: 'Synonyms or related terms (used for search)',
    }),
    color: Type.Optional(
      Type.String({
        description: 'string representation of a color in 24 bit (#rrggbb)',
        pattern: '^#[a-fA-F0-9]{6}$',
      }),
    ),
  },
  {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: 'http://mapeo.world/schemas/preset/v1.json',
    description:
      'Presets define how map entities are displayed to the user. They define the icon used on the map, and the fields / questions shown to the user when they create or edit the entity on the map. The `tags` property of a preset is used to match the preset with observations, nodes, ways and relations. If multiple presets match, the one that matches the most tags is used.',
    additionalProperties: false,
  },
)
