/**
 * ATTENTION. This code was AUTO GENERATED by schema2typebox.
 * While I don't know your use case, there is a high chance that direct changes
 * to this file get lost. Consider making changes to the underlying JSON schema
 * you use to generate this file instead. The default file is called
 * "schema.json", perhaps have a look there! :]
 */
import { Type } from '@sinclair/typebox'

export const Track = Type.Object(
  {
    docId: Type.String({
      description: 'Hex-encoded 32-byte buffer',
      minLength: 1,
    }),
    versionId: Type.String({
      description:
        "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
      minLength: 1,
    }),
    originalVersionId: Type.String({
      description:
        'Version ID of the original version of this document. For the original version, matches `versionId`.',
      minLength: 1,
    }),
    schemaName: Type.Literal('track', { description: 'Must be `track`' }),
    createdAt: Type.String({
      description:
        'RFC3339-formatted datetime of when the first version of the element was created',
      format: 'date-time',
    }),
    updatedAt: Type.String({
      description:
        'RFC3339-formatted datetime of when this version of the element was created',
      format: 'date-time',
    }),
    links: Type.Array(Type.String(), {
      description:
        "Version ids of the previous document versions this one is replacing. Each link is id (hex-encoded 32 byte buffer) and index number, separated by '/'",
      uniqueItems: true,
    }),
    deleted: Type.Boolean({
      description: 'Indicates whether the document has been deleted',
    }),
    locations: Type.Array(
      Type.Object(
        {
          timestamp: Type.String({
            description:
              'Timestamp (ISO date string) of when the current position was obtained',
            format: 'date-time',
          }),
          mocked: Type.Boolean({
            description: '`true` if the position was mocked',
            default: false,
          }),
          coords: Type.Object(
            {
              latitude: Type.Number(),
              longitude: Type.Number(),
              altitude: Type.Optional(Type.Number()),
              heading: Type.Optional(Type.Number()),
              speed: Type.Optional(Type.Number()),
              accuracy: Type.Optional(Type.Number()),
            },
            {
              description:
                'Position details, should be self explanatory. Units in meters',
            },
          ),
        },
        { description: 'Position details' },
      ),
      { description: 'Array of positions along the track' },
    ),
    observationRefs: Type.Array(
      Type.Object({
        docId: Type.String({
          description:
            'hex-encoded id of the element that this track references',
          minLength: 1,
        }),
        versionId: Type.String({
          description:
            "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
          minLength: 1,
        }),
      }),
      {
        description:
          'References to any observations that this track is related to.',
      },
    ),
    tags: Type.Record(
      Type.String(),
      Type.Union([
        Type.Boolean(),
        Type.Number(),
        Type.String(),
        Type.Null(),
        Type.Array(
          Type.Union([
            Type.Boolean(),
            Type.Number(),
            Type.String(),
            Type.Null(),
          ]),
        ),
      ]),
    ),
    presetRef: Type.Optional(
      Type.Object(
        {
          docId: Type.String({
            description:
              'hex-encoded id of the element that this track references',
            minLength: 1,
          }),
          versionId: Type.String({
            description:
              "core discovery id (hex-encoded 32-byte buffer) and core index number, separated by '/'",
            minLength: 1,
          }),
        },
        {
          description:
            'References to the preset that this track is related to.',
        },
      ),
    ),
  },
  {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: 'http://mapeo.world/schemas/track/v1.json',
    description:
      'A track is a recording of positions over time, with associated tags, similar to an observation',
    additionalProperties: false,
  },
)
